### ISSUE TITLE
[PE-D][Tester B] No instruction for note

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-2/tp#126] opened 2024-04-05 19:45 UTC
There is no instruction for not in UG.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Hibeom0929/ped#12

**Comment by AL-ZT** [comment] 2024-04-12 05:31
Duplicate of #152

**Closed by AL-ZT** 2024-04-12 05:31 UTC
Labels: bug
