### ISSUE TITLE
[PE-D][Tester D] Command History shows the command class constructor instead of actual command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-2/tp#117] opened 2024-04-05 18:46 UTC
Steps to reproduce:

1. Enter a few commands in the correct format, as stated in the user guide
2. Enter `history` into the command line

![image.png](https://raw.githubusercontent.com/yuechen2001/ped/main/files/61c1f7ca-fadf-42e6-98ca-cf23728cf908.png)

For someone who is not technically trained, I would imagine some difficulty in interpreting the command history. Perhaps a better way would be to show the formatted string (i.e. what the user has typed in), I think this would command history an excellent feature to have! 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yuechen2001/ped#4

**Comment by AL-ZT** [comment] 2024-04-07 07:34
Duplicate of #136

**Closed by AL-ZT** 2024-04-07 07:34 UTC
Labels: enhancement
